// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth/session/login": {
    params: {};
  };
  "/auth/session/refresh": {
    params: {};
  };
  "/auth/session/logout": {
    params: {};
  };
  "/auth/session/me": {
    params: {};
  };
  "/auth/session/register": {
    params: {};
  };
  "/auth/session/gateway/*": {
    params: {
      "*": string;
    };
  };
  "/auth/api/*": {
    params: {
      "*": string;
    };
  };
  "/product/*": {
    params: {
      "*": string;
    };
  };
  "/inventory/*": {
    params: {
      "*": string;
    };
  };
  "/order/*": {
    params: {
      "*": string;
    };
  };
  "/login": {
    params: {};
  };
  "/products": {
    params: {};
  };
  "/products/new": {
    params: {};
  };
  "/products/:id": {
    params: {
      "id": string;
    };
  };
  "/catalog": {
    params: {};
  };
  "/orders": {
    params: {};
  };
  "/coupons": {
    params: {};
  };
  "/analytics": {
    params: {};
  };
  "/users": {
    params: {};
  };
  "/users/new": {
    params: {};
  };
  "/users/:id": {
    params: {
      "id": string;
    };
  };
  "/settings": {
    params: {};
  };
};

type RouteFiles = {
  "root.js": {
    id: "root";
    page: "/" | "/auth/session/login" | "/auth/session/refresh" | "/auth/session/logout" | "/auth/session/me" | "/auth/session/register" | "/auth/session/gateway/*" | "/auth/api/*" | "/product/*" | "/inventory/*" | "/order/*" | "/login" | "/products" | "/products/new" | "/products/:id" | "/catalog" | "/orders" | "/coupons" | "/analytics" | "/users" | "/users/new" | "/users/:id" | "/settings";
  };
  "routes/auth.session.login.tsx": {
    id: "routes/auth.session.login";
    page: "/auth/session/login";
  };
  "routes/auth.session.refresh.tsx": {
    id: "routes/auth.session.refresh";
    page: "/auth/session/refresh";
  };
  "routes/auth.session.logout.tsx": {
    id: "routes/auth.session.logout";
    page: "/auth/session/logout";
  };
  "routes/auth.session.me.tsx": {
    id: "routes/auth.session.me";
    page: "/auth/session/me";
  };
  "routes/auth.session.register.tsx": {
    id: "routes/auth.session.register";
    page: "/auth/session/register";
  };
  "routes/auth.session.gateway.tsx": {
    id: "routes/auth.session.gateway";
    page: "/auth/session/gateway/*";
  };
  "routes/gateway.auth-api.tsx": {
    id: "routes/gateway.auth-api";
    page: "/auth/api/*";
  };
  "routes/gateway.product.tsx": {
    id: "routes/gateway.product";
    page: "/product/*";
  };
  "routes/gateway.inventory.tsx": {
    id: "routes/gateway.inventory";
    page: "/inventory/*";
  };
  "routes/gateway.order.tsx": {
    id: "routes/gateway.order";
    page: "/order/*";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/admin.tsx": {
    id: "routes/admin";
    page: "/" | "/products" | "/products/new" | "/products/:id" | "/catalog" | "/orders" | "/coupons" | "/analytics" | "/users" | "/users/new" | "/users/:id" | "/settings";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/";
  };
  "routes/products.tsx": {
    id: "routes/products";
    page: "/products";
  };
  "routes/products.new.tsx": {
    id: "routes/products.new";
    page: "/products/new";
  };
  "routes/products.$id.tsx": {
    id: "routes/products.$id";
    page: "/products/:id";
  };
  "routes/catalog.tsx": {
    id: "routes/catalog";
    page: "/catalog";
  };
  "routes/orders.tsx": {
    id: "routes/orders";
    page: "/orders";
  };
  "routes/coupons.tsx": {
    id: "routes/coupons";
    page: "/coupons";
  };
  "routes/analytics.tsx": {
    id: "routes/analytics";
    page: "/analytics";
  };
  "routes/users.tsx": {
    id: "routes/users";
    page: "/users";
  };
  "routes/users.new.tsx": {
    id: "routes/users.new";
    page: "/users/new";
  };
  "routes/users.$id.tsx": {
    id: "routes/users.$id";
    page: "/users/:id";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.js");
  "routes/auth.session.login": typeof import("./app/routes/auth.session.login.tsx");
  "routes/auth.session.refresh": typeof import("./app/routes/auth.session.refresh.tsx");
  "routes/auth.session.logout": typeof import("./app/routes/auth.session.logout.tsx");
  "routes/auth.session.me": typeof import("./app/routes/auth.session.me.tsx");
  "routes/auth.session.register": typeof import("./app/routes/auth.session.register.tsx");
  "routes/auth.session.gateway": typeof import("./app/routes/auth.session.gateway.tsx");
  "routes/gateway.auth-api": typeof import("./app/routes/gateway.auth-api.tsx");
  "routes/gateway.product": typeof import("./app/routes/gateway.product.tsx");
  "routes/gateway.inventory": typeof import("./app/routes/gateway.inventory.tsx");
  "routes/gateway.order": typeof import("./app/routes/gateway.order.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/admin": typeof import("./app/routes/admin.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/products": typeof import("./app/routes/products.tsx");
  "routes/products.new": typeof import("./app/routes/products.new.tsx");
  "routes/products.$id": typeof import("./app/routes/products.$id.tsx");
  "routes/catalog": typeof import("./app/routes/catalog.tsx");
  "routes/orders": typeof import("./app/routes/orders.tsx");
  "routes/coupons": typeof import("./app/routes/coupons.tsx");
  "routes/analytics": typeof import("./app/routes/analytics.tsx");
  "routes/users": typeof import("./app/routes/users.tsx");
  "routes/users.new": typeof import("./app/routes/users.new.tsx");
  "routes/users.$id": typeof import("./app/routes/users.$id.tsx");
  "routes/settings": typeof import("./app/routes/settings.tsx");
};