// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/products": {
    params: {};
  };
  "/products/new": {
    params: {};
  };
  "/products/:id": {
    params: {
      "id": string;
    };
  };
  "/orders": {
    params: {};
  };
  "/coupons": {
    params: {};
  };
  "/analytics": {
    params: {};
  };
  "/users": {
    params: {};
  };
  "/settings": {
    params: {};
  };
};

type RouteFiles = {
  "root.js": {
    id: "root";
    page: "/" | "/login" | "/products" | "/products/new" | "/products/:id" | "/orders" | "/coupons" | "/analytics" | "/users" | "/settings";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/admin.tsx": {
    id: "routes/admin";
    page: "/" | "/products" | "/products/new" | "/products/:id" | "/orders" | "/coupons" | "/analytics" | "/users" | "/settings";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/";
  };
  "routes/products.tsx": {
    id: "routes/products";
    page: "/products";
  };
  "routes/products.new.tsx": {
    id: "routes/products.new";
    page: "/products/new";
  };
  "routes/products.$id.tsx": {
    id: "routes/products.$id";
    page: "/products/:id";
  };
  "routes/orders.tsx": {
    id: "routes/orders";
    page: "/orders";
  };
  "routes/coupons.tsx": {
    id: "routes/coupons";
    page: "/coupons";
  };
  "routes/analytics.tsx": {
    id: "routes/analytics";
    page: "/analytics";
  };
  "routes/users.tsx": {
    id: "routes/users";
    page: "/users";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.js");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/admin": typeof import("./app/routes/admin.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/products": typeof import("./app/routes/products.tsx");
  "routes/products.new": typeof import("./app/routes/products.new.tsx");
  "routes/products.$id": typeof import("./app/routes/products.$id.tsx");
  "routes/orders": typeof import("./app/routes/orders.tsx");
  "routes/coupons": typeof import("./app/routes/coupons.tsx");
  "routes/analytics": typeof import("./app/routes/analytics.tsx");
  "routes/users": typeof import("./app/routes/users.tsx");
  "routes/settings": typeof import("./app/routes/settings.tsx");
};